version: "3.9"

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: meetup-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetup
    ports:
      - "5432:5432"
    volumes:
      - meetup-pgdata:/var/lib/postgresql/data

volumes:
  meetup-pgdata: